### ISSUE TITLE
No module named 'utils.bluetooth_utils'; 'utils' is not a package

### ISSUE THREAD

**Issue by AndreFal** [ECTO-1A/AppleJuice#3]
Cannot run it, facing the following error:

File "/home/kali/Tools/AppleJuice/Pair New Device Notifications/beatssolopro.py", line 16, in <module>
    from utils.bluetooth_utils import (toggle_device, start_le_advertising, stop_le_advertising)
ModuleNotFoundError: No module named 'utils.bluetooth_utils'; 'utils' is not a package

**Comment by ECTO-1A** [comment]
Try re-running these steps, that usually happens if the Bluetooth packages didn’t install properly. Also, reboot the machine after the install, others have reported needing to reboot in order for it to start working.


Install dependancies
sudo apt update && sudo apt install -y bluez libpcap-dev libev-dev libnl-3-dev libnl-genl-3-dev libnl-route-3-dev cmake libbluetooth-dev

Install pybluez && pycryptodome
The pybluez library is broken on Github and needs to be installed manually

download the latest version from pip install git+https://github.com/pybluez/pybluez.git#egg=pybluez
pycrypto is not maintained but you can install pycryptodome and it will work pip install pycryptodome

**Comment by AndreFal** [comment]
Purged and reinstalled everything following your steps. Rebooted the machine as well.
Unfortunately I'm facing the same issue.

**Comment by ECTO-1A** [comment]
Which OS are you running? I've only tested with Kali (works) and MacOS(didn't work)

**Comment by AndreFal** [comment]
I'm running kali in vm on Windows. I'm gonna test it now on kali (bare metal) if I have the same issue.

**Comment by m1ddl3w4r3** [comment]
Im having the same issue and cannot resolve it. Tried on kali VM and bare metal. also tried on popOS with no joy. Also your docs say there is a scripts folder but no folder exist in the repo?
